apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale-deployment-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"] # The API group for deployments
  resources: ["deployments", "deployments/scale"] # Access to deployments and their scale subresource
  verbs: ["get", "patch", "update"]  #  Allows getting, patching, and updating deployment scale

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-deployment-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: scale-deployment-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io

